name: WeasyPrint's PDF/UA tests
on: [push, pull_request]

env:
  REPORTS_FOLDER: 'report'

jobs:
  pdf-ua:
    name: Generate samples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip and setuptools
        run: python -m pip install --upgrade pip setuptools
      - name: Install requirements
        run: python -m pip install .
      - name: Clone samples repository
        run: git clone https://github.com/CourtBouillon/weasyprint-samples.git
      - name: Create output folder
        run: mkdir ${{env.REPORTS_FOLDER}}
      - name: Generate samples
        run: |
          python -m weasyprint --pdf-variant pdf/ua-1 weasyprint-samples/book/book.html -s weasyprint-samples/book/book-classical.css ${{env.REPORTS_FOLDER}}/book-classical.pdf
          python -m weasyprint --pdf-variant pdf/ua-1 weasyprint-samples/book/book.html -s weasyprint-samples/book/book.css ${{env.REPORTS_FOLDER}}/book-fancy.pdf
          python -m weasyprint --pdf-variant pdf/ua-1 weasyprint-samples/invoice/invoice.html ${{env.REPORTS_FOLDER}}/invoice.pdf
          python -m weasyprint --pdf-variant pdf/ua-1 weasyprint-samples/letter/letter.html ${{env.REPORTS_FOLDER}}/letter.pdf
          python -m weasyprint --pdf-variant pdf/ua-1 weasyprint-samples/poster/poster.html -s weasyprint-samples/poster/poster.css ${{env.REPORTS_FOLDER}}/poster.pdf
          python -m weasyprint --pdf-variant pdf/ua-1 weasyprint-samples/poster/poster.html -s weasyprint-samples/poster/flyer.css ${{env.REPORTS_FOLDER}}/flyer.pdf
          python -m weasyprint --pdf-variant pdf/ua-1 weasyprint-samples/report/report.html ${{env.REPORTS_FOLDER}}/report.pdf
          python -m weasyprint --pdf-variant pdf/ua-1 weasyprint-samples/ticket/ticket.html ${{env.REPORTS_FOLDER}}/ticket.pdf
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Generate VeraPDF reports
        uses: docker://verapdf/cli:latest
        run: |
          ./verapdf -f ua1 --success --progress --format html /github/workspace/${{env.REPORTS_FOLDER}}/report.pdf > /github/workspace/${{env.REPORTS_FOLDER}}/report-verapdf.html
      - name: Archive generated PDFs
        uses: actions/upload-artifact@v4
        with:
          name: generated-documents
          path: ${{env.REPORTS_FOLDER}}
          retention-days: 1
